CREATE PROC FI_SP_IncBeneficiario
	@IDCliente	   BIGINT		,
    @NOME          VARCHAR (50) ,
	@CPF		   VARCHAR (14) 
AS
BEGIN
	INSERT INTO BENEFICIARIOS(IDCLIENTE, CPF, NOME) 
	VALUES (@IDCliente, @CPF, @NOME);

	SELECT SCOPE_IDENTITY()
END